version: '3.8'

services:
  # Account Service
  account_primary:
    image: postgres:13
    container_name: account_primary
    environment:
      POSTGRES_USER: account
      POSTGRES_PASSWORD: account
      POSTGRES_DB: account
    volumes:
      - account_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

  account_redis:
    image: redis:latest
    container_name: account_redis
    ports:
      - "6379:6379"
    networks:
      - backend_network

  # Transaction Service
  transaction_primary:
    image: postgres:13
    container_name: transaction_primary
    environment:
      POSTGRES_USER: transaction
      POSTGRES_PASSWORD: transaction
      POSTGRES_DB: transaction
    volumes:
      - transaction_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend_network

  transaction_redis:
    image: redis:latest
    container_name: transaction_redis
    ports:
      - "6380:6379"
    networks:
      - backend_network

  rabbitmq:
    image: rabbitmq:3-management  # This image includes the management plugin
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"  # Port for web management interface
      - "5672:5672"    # Port for RabbitMQ server
    networks:
      - backend_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  seq:
    image: datalust/seq
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_USERNAME: "admin"
      SEQ_PASSWORD: "adminpassword"
    ports:
      - "5341:80"  # Default Seq web interface port
    networks:
      - backend_network
    volumes:
      - seq_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  account_data:
  account_replica_data:
  transaction_data:
  transaction_replica_data:
  rabbitmq_data:
  transaction_service_dev_data:
  account_service_dev_data:
  seq_data:

networks:
  backend_network:
    driver: bridge