@API_HostAddress = https://localhost:7101

### Create Account
POST {{API_HostAddress}}/account/create-account
Content-Type: application/json
Accept: application/json

### Get All Accounts
GET {{API_HostAddress}}/account/get-all-accounts
Accept: application/json